;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(beginning-of-visual-line
                               ruby-end-space
                               minibuffer-complete-and-exit))

(setq mc/cmds-to-run-once '(cua-set-mark
                            autopair-backspace))

                            
                               