;; (defun autopairs-ret (arg)
;;   (interactive "P")
;;   (let (pair)
;;     (dolist (pair skeleton-pair-alist)
;;       (when (eq (char-after) (car (last pair)))
;;         (save-excursion (newline-and-indent))))
;;     (newline arg)
;;     (indent-according-to-mode)))
;; (global-set-key (kbd "RET") 'autopairs-ret)

;; (autopair-global-mode t)
